### ISSUE TITLE
k3s support

### ISSUE THREAD

**Issue by maximilien** [knative-sandbox/kn-plugin-quickstart#240]
During a [live demo twitch stream today Knative](https://www.youtube.com/watch?v=v60iNvNfll4), I mentioned the quickstart plugin. One question from the audience was if [k3s](https://k3s.io) was supported or planned. I imagine might not be too hard :)

**Comment by psschwei** [comment]
No, not supported at the moment. 

Networking is always the fun part, especially on local systems. 

Just tried to quickly install on an out of the box [k3d cluster](https://k3d.io/), but the Kourier install fails with an `0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports` error. But only spent about 3 minutes with it at this point.

**Comment by csantanapr** [comment]
I don't think we should support `k3s` with the quickstart. 
k3s works fine with normal installation I have used it in [raspberry pi](https://github.com/csantanapr/knative-pi) 

I saw the stream and JJ asked for k3s not k3d. 

On purpose, we started only with `kind` because it covers users with windows, linux, and mac. 
We were not planning to support docker desktop or minikube, but with the recent change in license on Docker Desktop we decided to support a second option and we choose minikube which is supported on multiple of platforms with many drivers.

The k3d option is another potential target, the same with Rancher Desktop, and Docker Desktop. 
I'm worry that we stretch too thin on supporting too many options, and then we end up with too many things to maintain and keep current. 
Also add complexity on documentation, the user today not sure which one is better to use between `kind` or `minikube` if we add more option then is more permutations to add.

I think maintaining and testing the current targets `kind` and `minikube` is enough, and today we don't have any automation testing or CI in place. I think after testing and automation testing is in place then adding the third target is an option we can take a look.

**Comment by psschwei** [comment]
Agreed that keeping the number of install options small is for the best. 

If install size is an issue (which seems to be one of the main k3s use cases), dropping the knative resource requests (as discussed in #104 ) is probably the solution we'd want to pursue.

That said, maybe option 3 (if we ever get there) is to install on a pre-existing cluster (i.e. you've already set up your Docker Desktop or Rancher or k3d cluster) and quickstart just installs the Knative resources...

**Comment by maximilien** [comment]
I like @psschwei suggestion ^^^. Closing.
