### ISSUE TITLE
Default minikube/knative memory/cpu configuration

### ISSUE THREAD

**Issue by gansheer** [knative-sandbox/kn-plugin-quickstart#382]
I am having some trouble with the default values used to start minikube ([3 GB memory/3 CPUs](https://github.com/knative-sandbox/kn-plugin-quickstart/blob/main/pkg/minikube/minikube.go) or [6GB memory/3CPUs](https://knative.dev/docs/install/quickstart-install/#run-the-knative-quickstart-plugin) - that's not clear which one). My troubles' source is that I have a very resources consuming use case, but while I was doing some search on the subject of minikube/knative I found this [recommendation](https://minikube.sigs.k8s.io/docs/faq/#what-is-the-minimum-resource-allocation-necessary-for-a-knative-setup-using-minikube) on minikube's documentation that recommends  6 CPUs and 8G memory.

I know that these values can be changed in the minikube config, but shouldn't the current default CPU/Mem values be changed to match the recommendation ?

**Comment by psschwei** [comment]
Thanks for pointing out the discrepancies! 

Our recommended at least 3 GB/cpus when running on minikube -- will work on getting all the docs to be in agreement. (the minikube docs rec looks to have been there for a while, probably back when Istio was a hard requirement, which ramped up the memory needs)

As for why 3 GB: we default to that in quickstart as that's the minimum that's needed to get an environment up and running with all the Knative components along with a couple of applications (for example, the ones from the tutorial). We err on the side of being low so that we won't break users with smaller machines. For example, if someone only has 8 GB of RAM, their cluster would never come up...

One last thing to note: quickstart really isn't meant for much more than a demo environment (i.e. not prod), so since you mentioned a resource-heavy use case just wanted to call that out in case you weren't aware.

**Comment by psschwei** [comment]
Cool -- thanks again for pointing out the issue
