### ISSUE TITLE
Shouldn't version 1.8.2 be 1.9.2?

### ISSUE THREAD

**Issue by gnarea** [knative-sandbox/kn-plugin-quickstart#406]
Looks like a mistake to me: https://github.com/knative-sandbox/kn-plugin-quickstart/releases/tag/knative-v1.8.2

I just have some code in CI that installs all Knative-related components using a common version, so I can't upgrade to v1.9.2.

**Comment by psschwei** [comment]
v1.8.2 is on the release-1.8 branch, so that's not a mistake. However, it shouldn't be marked as the latest release (that would be v1.9.1)... I've fixed that on GitHub.

Also, it's worth noting that Knative components won't necessarily be on the same patch version... for example, Serving could be on v1.9.2 whereas Quickstart might still be on v1.9.1 and Eventing could be on v1.9.3 . Major and minor versions  (e.g. v1.9) should always be the same for all components though

**Comment by gnarea** [comment]
Makes sense! Thanks @psschwei 👍🏾
